version: "3.7"

services:
  
  search-api:
    environment:
      - HOST_GID=${HOST_GID:-1000}
      - HOST_UID=${HOST_UID:-1000}
    volumes:
      # Mount the source code to container
      - "../src:/usr/src/app/src"
