name: CI Build

on:
  push:
    branches: [ "main", "dev-integrate" ]
  pull_request:
    branches: [ "main", "dev-integrate" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
        working-directory: src

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
        working-directory: src

      - name: Run tests
        run: ./test.sh